services:
  - type: web
    name: italian-drill
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ITALIAN_DRILL_DATA_DIR
        value: /opt/render/project/src/italian_drill_data
      - key: PYTHON_VERSION
        value: "3.11"
